### ISSUE TITLE
Please, can you tell me how to run this program

### ISSUE THREAD

**Issue by roodra186** [Nomiizz/Traffic-Intersection-Problem#1]
Sorry, but i don't know how to run this program. Please help me.

**Comment by roodra186** [comment]
Please help me

**Comment by Nomiizz** [comment]
Hello. This program was implemented as part of the OS161 teaching operating system. The files uploaded were the files in the OS that were modified since it was not feasible to upload the whole OS kernel. You can use these guides if you wish to setup OS161: https://student.cs.uwaterloo.ca/~cs350/common/WorkingWith161.html and https://student.cs.uwaterloo.ca/~cs350/common/Install161NonCS.html

**Comment by roodra186** [comment]
Thanks :)

**Comment by Nomiizz** [comment]
No problem
